#ShimejiEE preferences
#Sun Jul 26 22:34:06 CDT 2026
ActiveShimeji=Serial+Designation+V/Uzi+Doorman/Serial+Designation+N/
AlwaysShowShimejiChooser=true
Breeding=false
Throwing=true
Transformation=false
Transients=false
